### Import nesssary model

In [1]:
import pandas as pd
import numpy as np
from IPython.display import Image
np.set_printoptions(precision = 3)

### Load data

In [3]:
data = pd.read_csv("jester-data-1.csv", header=None)
#d = data.to_latex()
#text_file = open("Output_lab4_test.txt", "w")
#text_file.write(d)
#text_file.close()

In [4]:
data.head()

0      1      2      3      4     5     6     7     8      9    ...    \
0   74  -7.82   8.79  -9.66  -8.16 -7.52 -8.50 -9.85  4.17  -8.98  ...     
1  100   4.08  -0.29   6.36   4.37 -2.38 -9.66 -0.73 -5.34   8.88  ...     
2   49  99.00  99.00  99.00  99.00  9.03  9.27  9.03  9.27  99.00  ...     
3   48  99.00   8.35  99.00  99.00  1.80  8.16 -2.82  6.21  99.00  ...     
4   91   8.50   4.61  -4.17  -5.39  1.36  1.60  7.04  4.61  -0.44  ...     

     91     92     93     94     95     96     97     98     99     100  
0   2.82  99.00  99.00  99.00  99.00  99.00  -5.63  99.00  99.00  99.00  
1   2.82  -4.95  -0.29   7.86  -0.19  -2.14   3.06   0.34  -4.32   1.07  
2  99.00  99.00  99.00   9.08  99.00  99.00  99.00  99.00  99.00  99.00  
3  99.00  99.00  99.00   0.53  99.00  99.00  99.00  99.00  99.00  99.00  
4   5.19   5.58   4.27   5.19   5.73   1.55   3.11   6.55   1.80   1.60  

[5 rows x 101 columns]

### Prepare the dataset

In [5]:
#user_ratings = data.values
user_ratings = data.values[0:100]

In [6]:
user_ratings_vali = np.zeros(user_ratings.shape) + 99.0
user_ratings_copy = user_ratings.copy() 
count = 0
for x in range(0,user_ratings.shape[0]):
    for y in range(0,user_ratings.shape[1]):
        if (user_ratings_copy[x,y]!=99.0):
            if (np.random.random() > 0.9):
                count += 1
                temp = user_ratings_copy[x,y]
                user_ratings_copy[x,y] = user_ratings_vali[x,y]
                user_ratings_vali[x,y] = temp
                #print(temp)
print(user_ratings_vali,'\n', count,'\n', count/(user_ratings.shape[0]*user_ratings.shape[1]))

[[99.   99.   99.   ... 99.   99.   99.  ]
 [99.   99.   99.   ... 99.   99.    1.07]
 [49.   99.   99.   ... 99.   99.   99.  ]
 ...
 [37.   99.   99.   ... 99.   99.   99.  ]
 [99.   99.   99.   ... 99.   99.   99.  ]
 [99.   99.   99.   ... 99.   99.   99.  ]] 
 716 
 0.07089108910891088


### Prepare the predicte matrix

In [7]:
n_features = 10
latent_user_preferences = np.random.random((user_ratings.shape[0], n_features))
latent_item_features = np.random.random((user_ratings.shape[1],n_features))

In [8]:
print('user_ratings.shape:           ',user_ratings.shape)
print('latent_user_preferences.shape:',latent_user_preferences.shape)
print('latent_item_features.shape:   ',latent_item_features.shape)

user_ratings.shape:            (100, 101)
latent_user_preferences.shape: (100, 10)
latent_item_features.shape:    (101, 10)


In [9]:
user_ratings, user_ratings.shape

(array([[ 74.  ,  -7.82,   8.79, ...,  99.  ,  99.  ,  99.  ],
        [100.  ,   4.08,  -0.29, ...,   0.34,  -4.32,   1.07],
        [ 49.  ,  99.  ,  99.  , ...,  99.  ,  99.  ,  99.  ],
        ...,
        [ 37.  ,  99.  ,  99.  , ...,  99.  ,  99.  ,  99.  ],
        [100.  ,   3.3 ,   1.31, ...,  -0.44,   1.17,   6.5 ],
        [ 37.  ,  99.  ,  99.  , ...,  99.  ,  99.  ,  99.  ]]), (100, 101))

In [10]:
np.random.random()

0.13755475885257595

### Training function

In [11]:
def predict_rating(user_id,item_id):
    """ Predict a rating given a user_id and an item_id.
    """
    user_preference = latent_user_preferences[user_id]
    item_preference = latent_item_features[item_id]
    return user_preference.dot(item_preference)  #linear

def train(user_id, item_id, rating,alpha = 0.0001):
    
    #print (item_id)
    prediction_rating = predict_rating(user_id, item_id)
    err =  ( prediction_rating- rating );
    #print (err)
    user_pref_values = latent_user_preferences[user_id][:]
    latent_user_preferences[user_id] -= alpha * err * latent_item_features[item_id]
    latent_item_features[item_id] -= alpha * err * user_pref_values
    return err
    


def sgd(iterations = 100000):
    """ Iterate over all users and all items and train for 
        a certain number of iterations
    """
    err_mse_log = 0
    for iteration in range(0,iterations):
        error = []
        for user_id in range(0,latent_user_preferences.shape[0]):
            for item_id in range(0,latent_item_features.shape[0]):
                rating = user_ratings_copy[user_id][item_id]
                if(rating != 99.0):
                    err = train(user_id,item_id,rating)
                    error.append(err)
                    #print(rating)
        mse = (np.array(error) ** 2).mean()
        #print(iteration)
        if(iteration%1000 == 0 ):
            err_mse = mse - err_mse_log
            err_mse_log = mse
            print (iteration, ':=', mse, err_mse)
                    
                    
    

In [12]:
sgd()

0 := 102.30180346764722 102.30180346764722
1000 := 9.595917991327335 -92.70588547631988
2000 := 9.134672057539275 -0.4612459337880601
3000 := 9.028114147209708 -0.10655791032956685
4000 := 8.973169409423905 -0.054944737785803
5000 := 8.933048600685513 -0.040120808738391744
6000 := 8.892632102963233 -0.04041649772227984
7000 := 8.847585531328326 -0.04504657163490755
8000 := 8.805828869983673 -0.04175666134465317
9000 := 8.774613700378291 -0.031215169605381732
10000 := 8.752412978163694 -0.022200722214597235
11000 := 8.735910025688087 -0.016502952475606847
12000 := 8.723168296670314 -0.012741729017772485
13000 := 8.713202285305572 -0.0099660113647424
14000 := 8.705386063315386 -0.007816221990186278
15000 := 8.699238968199403 -0.006147095115982992
16000 := 8.694372026576524 -0.00486694162287904
17000 := 8.690472286372662 -0.0038997402038614126
18000 := 8.687294667685572 -0.003177618687089989
19000 := 8.684653716352472 -0.002640951333100716
20000 := 8.682413479602733 -0.0022402367497385
21

KeyboardInterrupt: 

In [13]:
latent_user_preferences

array([[ 5.964e-01,  5.393e-01,  8.924e-03,  4.249e-01,  1.077e+00,
         2.537e-02,  2.737e-01,  1.572e+00, -1.927e+00,  3.888e+00],
       [ 4.596e-01,  1.592e-02, -3.088e-01,  1.288e+00,  9.453e-01,
         7.358e-01,  1.702e-01,  1.472e+00,  2.284e+00,  2.977e-01],
       [ 7.029e-01,  9.870e-02,  2.682e+00,  1.152e+00,  1.421e+00,
         4.819e-01,  1.168e+00,  1.818e+00,  1.086e+00, -1.066e+00],
       [ 1.772e+00, -6.514e-01,  1.158e+00,  1.953e-01,  1.012e+00,
         3.269e-01, -9.631e-01, -1.347e-01,  7.868e-01,  1.564e+00],
       [ 1.983e+00,  6.249e-01,  1.444e+00,  4.757e-02,  1.284e+00,
         5.765e-01,  3.602e-01,  1.131e+00,  3.257e-01,  3.799e-01],
       [ 9.870e-01,  2.201e+00, -1.054e+00,  9.787e-01, -2.617e-01,
         8.402e-01,  2.110e-02, -2.112e-01,  5.256e-01,  2.476e+00],
       [ 1.365e+00, -9.676e-02,  1.344e+00,  6.847e-01,  6.052e-01,
         4.828e-02,  9.284e-01,  7.552e-01, -2.831e-01, -9.613e-01],
       [ 1.665e+00,  1.927e+00,  2.804e-0

In [14]:
predictions = latent_user_preferences.dot(latent_item_features.T)
predictions

array([[ 7.406e+01, -7.200e+00,  6.095e+00, ...,  1.467e+00,  1.279e+00,
        -4.056e+00],
       [ 1.004e+02,  3.118e+00,  1.858e-01, ...,  1.797e+00, -5.674e+00,
         2.551e+00],
       [ 1.042e+02,  8.710e+00,  8.677e+00, ...,  8.534e+00,  9.591e+00,
         6.511e+00],
       ...,
       [ 1.203e+03,  5.639e+01, -7.627e+00, ..., -2.196e+01, -1.430e+01,
        -1.298e+01],
       [ 9.925e+01,  3.598e+00,  7.352e-03, ..., -1.928e+00,  1.851e+00,
        -9.157e-02],
       [ 3.706e+01, -2.005e+00, -4.604e+00, ..., -6.252e-01, -6.718e+00,
        -3.503e+00]])

In [15]:
values = [zip(user_ratings_copy[i], predictions[i]) for i in range(0,predictions.shape[0])]
comparison_data = pd.DataFrame(values)
comparison_data.columns = data.columns
comparison_data.applymap(lambda x: "(%2.3f|%2.3f)"%(x[0],x[1]))
#comparison_data.head()

0                 1                 2                 3    \
0     (74.000|74.059)   (-7.820|-7.200)     (8.790|6.095)  (-9.660|-10.718)   
1   (100.000|100.354)     (4.080|3.118)    (-0.290|0.186)     (6.360|4.832)   
2    (99.000|104.159)    (99.000|8.710)    (99.000|8.677)    (99.000|5.704)   
3     (48.000|48.129)    (99.000|0.327)     (8.350|5.235)    (99.000|0.692)   
4     (91.000|91.029)    (99.000|6.085)     (4.610|4.548)    (-4.170|4.051)   
5    (100.000|99.554)   (-6.170|-2.763)   (-3.540|-6.454)    (0.440|-3.316)   
6     (47.000|47.464)    (99.000|9.097)    (99.000|4.301)    (99.000|5.075)   
7   (100.000|100.031)     (6.840|4.190)     (3.160|1.231)     (9.170|7.270)   
8     (99.000|89.699)   (-3.790|-3.203)   (-3.540|-3.135)   (-9.420|-5.370)   
9     (72.000|71.762)     (3.010|5.359)     (5.150|5.918)    (99.000|3.555)   
10    (36.000|35.955)   (-2.910|-0.244)     (4.080|4.662)    (99.000|3.255)   
11   (100.000|99.162)     (1.310|2.697)     (1.800|1.714)     (2.570|2.152)   
12    (47.000|47.308)    (99.000|4.338)    (99.000|6.487)    (99.000|2.351)   
13   (99.000|322.528)     (9.220|9.306)    (99.000|0.438)    (9.220|12.196)   
14   (100.000|99.935)   (99.000|12.355)   (-5.780|-4.846)     (6.020|6.371)   
15   (100.000|99.438)    (-3.500|0.545)     (1.550|2.886)     (2.330|0.319)   
16    (51.000|51.076)   (99.000|-3.525)   (-9.270|-4.945)    (99.000|1.371)   
17    (99.000|12.208)     (3.160|2.855)     (7.620|4.608)     (3.790|3.744)   
18    (49.000|48.864)     (4.220|2.320)     (3.640|1.679)    (99.000|2.272)   
19    (53.000|53.122)    (99.000|0.228)     (7.620|3.911)    (99.000|8.400)   
20    (55.000|55.059)     (2.570|0.649)   (-0.730|-0.276)   (99.000|-0.383)   
21    (50.000|50.107)     (7.280|5.271)    (99.000|4.795)    (99.000|5.230)   
22    (72.000|72.923)     (2.720|3.909)     (4.170|9.263)     (6.500|4.847)   
23  (100.000|100.312)    (2.090|-0.188)   (-7.570|-1.580)    (4.170|-4.170)   
24    (74.000|74.192)   (-3.930|-0.104)    (-1.170|0.927)    (2.280|-1.844)   
25    (99.000|-0.989)    (99.000|5.487)     (5.490|5.724)     (3.450|4.394)   
26    (99.000|40.289)    (99.000|3.288)     (5.830|5.597)   (99.000|-1.208)   
27    (72.000|72.298)    (0.490|-2.298)     (0.150|1.353)    (0.150|-2.117)   
28    (54.000|53.851)   (99.000|-0.135)    (99.000|1.603)   (99.000|-4.406)   
29    (46.000|46.086)    (99.000|3.462)     (4.080|4.365)    (99.000|4.672)   
..                ...               ...               ...               ...   
70  (100.000|100.313)     (3.500|2.453)     (6.210|0.955)    (-0.630|1.169)   
71    (68.000|68.124)   (-6.210|-1.202)   (-0.100|-5.723)   (-5.290|-4.069)   
72   (100.000|99.780)    (5.440|-0.776)   (-2.670|-7.447)   (-7.960|-3.359)   
73    (67.000|66.889)     (9.270|5.617)     (9.170|9.584)     (9.270|9.313)   
74  (100.000|100.995)    (2.380|-0.653)   (-5.440|-3.523)   (-8.110|-4.444)   
75    (48.000|47.991)   (99.000|24.201)  (99.000|-27.307)   (99.000|22.247)   
76   (100.000|99.868)  (-8.500|-10.532)   (-6.600|-4.671)   (-8.450|-7.317)   
77    (55.000|55.015)    (99.000|8.926)    (99.000|4.220)    (99.000|5.925)   
78  (100.000|100.025)    (99.000|1.008)    (1.700|-2.342)   (-5.530|-5.159)   
79    (53.000|53.025)    (99.000|1.298)    (99.000|0.742)    (99.000|2.522)   
80    (38.000|37.943)    (99.000|3.439)   (99.000|-2.961)    (99.000|4.065)   
81    (53.000|52.965)    (3.450|-2.658)     (6.070|3.884)   (-9.270|-6.198)   
82  (100.000|100.474)     (3.060|1.057)    (6.500|10.199)   (-7.910|-6.926)   
83    (72.000|72.489)   (-7.670|-2.634)    (-6.990|1.375)    (99.000|1.594)   
84    (41.000|41.188)    (99.000|2.674)    (99.000|3.282)   (99.000|-1.577)   
85     (99.000|5.705)   (-1.500|-3.766)    (3.300|-0.121)   (99.000|-4.969)   
86   (100.000|99.479)     (2.820|7.622)     (5.440|5.008)     (7.570|4.107)   
87    (74.000|74.446)     (6.890|0.543)   (-9.660|-5.144)    (0.150|-0.432)   
88    (72.000|72.056)   (-6.070|-0.687)   (-5.580|-2.758)   (-6.170|

In [16]:
values = [zip(user_ratings_vali[i], predictions[i]) for i in range(0,predictions.shape[0])]
comparison_data = pd.DataFrame(values)
comparison_data_err = []
for x in range(0, comparison_data.shape[1]):
    for y in range(0, comparison_data.shape[0]):
        if (comparison_data[x][y][0] == 99.0):
            comparison_data[x][y] = (0,0)
        else:
            comparison_data_err.append(comparison_data[x][y][0] - comparison_data[x][y][1])
mse = (np.array(comparison_data_err) ** 2).mean()
comparison_data.columns = data.columns
comparison_data.applymap(lambda x: ["(%2.3f|%2.3f)"%(x[0],x[1]) ])

0                 1                2                 3    \
0       [(0.000|0.000)]   [(0.000|0.000)]  [(0.000|0.000)]   [(0.000|0.000)]   
1       [(0.000|0.000)]   [(0.000|0.000)]  [(0.000|0.000)]   [(0.000|0.000)]   
2    [(49.000|104.159)]   [(0.000|0.000)]  [(0.000|0.000)]   [(0.000|0.000)]   
3       [(0.000|0.000)]   [(0.000|0.000)]  [(0.000|0.000)]   [(0.000|0.000)]   
4       [(0.000|0.000)]   [(8.500|6.085)]  [(0.000|0.000)]   [(0.000|0.000)]   
5       [(0.000|0.000)]   [(0.000|0.000)]  [(0.000|0.000)]   [(0.000|0.000)]   
6       [(0.000|0.000)]   [(0.000|0.000)]  [(0.000|0.000)]   [(0.000|0.000)]   
7       [(0.000|0.000)]   [(0.000|0.000)]  [(0.000|0.000)]   [(0.000|0.000)]   
8    [(100.000|89.699)]   [(0.000|0.000)]  [(0.000|0.000)]   [(0.000|0.000)]   
9       [(0.000|0.000)]   [(0.000|0.000)]  [(0.000|0.000)]   [(5.150|3.555)]   
10      [(0.000|0.000)]   [(0.000|0.000)]  [(0.000|0.000)]   [(0.000|0.000)]   
11      [(0.000|0.000)]   [(0.000|0.000)]  [(0.000|0.000)]   [(0.000|0.000)]   
12      [(0.000|0.000)]   [(0.000|0.000)]  [(0.000|0.000)]   [(0.000|0.000)]   
13  [(100.000|322.528)]   [(0.000|0.000)]  [(9.270|0.438)]   [(0.000|0.000)]   
14      [(0.000|0.000)]  [(8.790|12.355)]  [(0.000|0.000)]   [(0.000|0.000)]   
15      [(0.000|0.000)]   [(0.000|0.000)]  [(0.000|0.000)]   [(0.000|0.000)]   
16      [(0.000|0.000)]   [(0.000|0.000)]  [(0.000|0.000)]   [(0.000|0.000)]   
17   [(100.000|12.208)]   [(0.000|0.000)]  [(0.000|0.000)]   [(0.000|0.000)]   
18      [(0.000|0.000)]   [(0.000|0.000)]  [(0.000|0.000)]   [(0.000|0.000)]   
19      [(0.000|0.000)]   [(0.000|0.000)]  [(0.000|0.000)]   [(0.000|0.000)]   
20      [(0.000|0.000)]   [(0.000|0.000)]  [(0.000|0.000)]   [(0.000|0.000)]   
21      [(0.000|0.000)]   [(0.000|0.000)]  [(5.390|4.795)]   [(0.000|0.000)]   
22      [(0.000|0.000)]   [(0.000|0.000)]  [(0.000|0.000)]   [(0.000|0.000)]   
23      [(0.000|0.000)]   [(0.000|0.000)]  [(0.000|0.000)]   [(0.000|0.000)]   
24      [(0.000|0.000)]   [(0.000|0.000)]  [(0.000|0.000)]   [(0.000|0.000)]   
25    [(67.000|-0.989)]   [(0.000|0.000)]  [(0.000|0.000)]   [(0.000|0.000)]   
26    [(60.000|40.289)]   [(0.000|0.000)]  [(0.000|0.000)]   [(0.000|0.000)]   
27      [(0.000|0.000)]   [(0.000|0.000)]  [(0.000|0.000)]   [(0.000|0.000)]   
28      [(0.000|0.000)]   [(0.000|0.000)]  [(0.000|0.000)]   [(0.000|0.000)]   
29      [(0.000|0.000)]   [(0.000|0.000)]  [(0.000|0.000)]   [(0.000|0.000)]   
..                  ...               ...              ...               ...   
70      [(0.000|0.000)]   [(0.000|0.000)]  [(0.000|0.000)]   [(0.000|0.000)]   
71      [(0.000|0.000)]   [(0.000|0.000)]  [(0.000|0.000)]   [(0.000|0.000)]   
72      [(0.000|0.000)]   [(0.000|0.000)]  [(0.000|0.000)]   [(0.000|0.000)]   
73      [(0.000|0.000)]   [(0.000|0.000)]  [(0.000|0.000)]   [(0.000|0.000)]   
74      [(0.000|0.000)]   [(0.000|0.000)]  [(0.000|0.000)]   [(0.000|0.000)]   
75      [(0.000|0.000)]   [(0.000|0.000)]  [(0.000|0.000)]   [(0.000|0.000)]   
76      [(0.000|0.000)]   [(0.000|0.000)]  [(0.000|0.000)]   [(0.000|0.000)]   
77      [(0.000|0.000)]   [(0.000|0.000)]  [(0.000|0.000)]   [(0.000|0.000)]   
78      [(0.000|0.000)]   [(2.280|1.008)]  [(0.000|0.000)]   [(0.000|0.000)]   
79      [(0.000|0.000)]   [(0.000|0.000)]  [(0.000|0.000)]   [(0.000|0.000)]   
80      [(0.000|0.000)]   [(0.000|0.000)]  [(0.000|0.000)]   [(0.000|0.000)]   
81      [(0.000|0.000)]   [(0.000|0.000)]  [(0.000|0.000)]   [(0.000|0.000)]   
82      [(0.000|0.000)]   [(0.000|0.000)]  [(0.000|0.000)]   [(0.000|0.000)]   
83      [(0.000|0.000)]   [(0.000|0.000)]  [(0.000|0.000)]  [(-1.410|1.594)]   
84      [(0.000|0.000)]   [(0.000|0.000)]  [(0.000|0.000)]   [(0.000|0.000)]   
85     [(72.000|5.705)]   [(0.000|0.000)]  [(0.000|0.000)]  [(3.350|-4.969)]   
86      [(0.000|0.000)]   [(0.000|0.000)]  [(0.000|0.000)]   [(0.000|0.000)]   
87      [(0.000|0.000)]   [(0.000|0.000)]  [(0.000|0.000)]   [(0.000|0.000)]   
88      [(0.000|0.00

In [17]:
mse


2077.9401353703

In [ ]:
predictions

In [ ]:
latent_item_features

In [18]:
np.savetxt("predictions_10f_10.csv", predictions, delimiter=",")
np.savetxt("latent_user_preferences_10f_10.csv", latent_user_preferences, delimiter=",")
np.savetxt("latent_item_features_10f_10.csv", latent_item_features, delimiter=",")