In [1]:
import pandas as pd
import numpy as np
from IPython.display import Image
np.set_printoptions(precision = 3)

In [4]:
data = pd.read_csv("jester-data-1.csv", header=None)
d = data.to_latex()
text_file = open("Output_lab4_test.txt", "w")
text_file.write(d)
text_file.close()

In [58]:
data.head()

0      1      2      3      4     5     6     7     8      9    ...    \
0   74  -7.82   8.79  -9.66  -8.16 -7.52 -8.50 -9.85  4.17  -8.98  ...     
1  100   4.08  -0.29   6.36   4.37 -2.38 -9.66 -0.73 -5.34   8.88  ...     
2   49  99.00  99.00  99.00  99.00  9.03  9.27  9.03  9.27  99.00  ...     
3   48  99.00   8.35  99.00  99.00  1.80  8.16 -2.82  6.21  99.00  ...     
4   91   8.50   4.61  -4.17  -5.39  1.36  1.60  7.04  4.61  -0.44  ...     

     91     92     93     94     95     96     97     98     99     100  
0   2.82  99.00  99.00  99.00  99.00  99.00  -5.63  99.00  99.00  99.00  
1   2.82  -4.95  -0.29   7.86  -0.19  -2.14   3.06   0.34  -4.32   1.07  
2  99.00  99.00  99.00   9.08  99.00  99.00  99.00  99.00  99.00  99.00  
3  99.00  99.00  99.00   0.53  99.00  99.00  99.00  99.00  99.00  99.00  
4   5.19   5.58   4.27   5.19   5.73   1.55   3.11   6.55   1.80   1.60  

[5 rows x 101 columns]

In [109]:
n_features = 5
#user_ratings = data.values
user_ratings = data.values[0:100]
latent_user_preferences = np.random.random((user_ratings.shape[0], n_features))
latent_item_features = np.random.random((user_ratings.shape[1],n_features))

In [110]:
print('user_ratings.shape:           ',user_ratings.shape)
print('latent_user_preferences.shape:',latent_user_preferences.shape)
print('latent_item_features.shape:   ',latent_item_features.shape)

user_ratings.shape:            (100, 101)
latent_user_preferences.shape: (100, 5)
latent_item_features.shape:    (101, 5)


In [90]:
latent_user_preferences

array([[0.526, 0.424, 0.052, 0.479, 0.433],
       [0.932, 0.131, 0.106, 0.373, 0.775],
       [0.724, 0.658, 0.36 , 0.284, 0.761],
       [0.038, 0.778, 0.924, 0.581, 0.971],
       [0.563, 0.741, 0.275, 0.35 , 0.448],
       [0.253, 0.883, 0.389, 0.202, 0.297],
       [0.696, 0.969, 0.014, 0.193, 0.88 ],
       [0.266, 0.465, 0.479, 0.655, 0.122],
       [0.332, 0.93 , 0.788, 0.022, 0.216],
       [0.48 , 0.749, 0.978, 0.57 , 0.93 ],
       [0.095, 0.714, 0.425, 0.249, 0.224],
       [0.769, 0.102, 0.101, 0.549, 0.945],
       [0.123, 0.544, 0.548, 0.96 , 0.155],
       [0.09 , 0.206, 0.767, 0.379, 0.701],
       [0.352, 0.84 , 0.413, 0.752, 0.725],
       [0.135, 0.022, 0.373, 0.351, 0.15 ],
       [0.177, 0.221, 0.521, 0.957, 0.53 ],
       [0.43 , 0.994, 0.901, 0.797, 0.602],
       [0.228, 0.576, 0.341, 0.569, 0.226],
       [0.695, 0.797, 0.847, 0.316, 0.935],
       [0.975, 0.353, 0.349, 0.315, 0.284],
       [0.91 , 0.907, 0.273, 0.339, 0.033],
       [0.151, 0.609, 0.907, 0.1

In [91]:
latent_item_features

array([[2.115e-01, 4.609e-01, 9.649e-01, 6.176e-01, 9.200e-01],
       [8.297e-01, 2.654e-01, 6.680e-01, 5.193e-01, 4.262e-01],
       [7.614e-01, 7.328e-02, 8.318e-01, 3.881e-01, 9.336e-01],
       [5.494e-01, 8.722e-01, 7.368e-01, 1.867e-01, 3.292e-01],
       [6.589e-01, 6.615e-02, 8.057e-01, 5.971e-01, 1.240e-01],
       [4.643e-01, 5.992e-01, 3.021e-02, 8.427e-01, 9.811e-02],
       [4.754e-01, 9.579e-01, 5.786e-01, 1.602e-01, 7.126e-01],
       [2.491e-01, 7.233e-01, 3.565e-01, 7.562e-01, 1.607e-01],
       [3.822e-01, 8.420e-02, 8.855e-01, 8.246e-01, 6.085e-01],
       [8.131e-01, 5.850e-01, 9.465e-01, 4.875e-01, 6.710e-01],
       [6.824e-01, 4.023e-01, 4.816e-01, 4.066e-01, 6.365e-02],
       [9.157e-01, 7.014e-01, 3.163e-02, 5.538e-01, 7.950e-01],
       [8.965e-01, 5.791e-02, 9.221e-01, 6.754e-01, 6.992e-02],
       [5.616e-01, 3.827e-01, 9.283e-01, 6.165e-01, 4.371e-01],
       [4.822e-01, 5.334e-01, 7.531e-01, 3.286e-01, 7.250e-01],
       [3.920e-02, 5.586e-01, 5.000e-01,

In [111]:
user_ratings, user_ratings.shape

(array([[ 74.  ,  -7.82,   8.79, ...,  99.  ,  99.  ,  99.  ],
        [100.  ,   4.08,  -0.29, ...,   0.34,  -4.32,   1.07],
        [ 49.  ,  99.  ,  99.  , ...,  99.  ,  99.  ,  99.  ],
        ...,
        [ 37.  ,  99.  ,  99.  , ...,  99.  ,  99.  ,  99.  ],
        [100.  ,   3.3 ,   1.31, ...,  -0.44,   1.17,   6.5 ],
        [ 37.  ,  99.  ,  99.  , ...,  99.  ,  99.  ,  99.  ]]), (100, 101))

In [112]:
np.random.random()

0.6743888589513028

In [113]:
user_ratings_vali = np.zeros(user_ratings.shape) + 99.0
user_ratings_copy = user_ratings.copy() 
count = 0
for x in range(0,user_ratings.shape[0]):
    for y in range(0,user_ratings.shape[1]):
        if (user_ratings_copy[x,y]!=99.0):
            if (np.random.random() > 0.9):
                count += 1
                temp = user_ratings_copy[x,y]
                user_ratings_copy[x,y] = user_ratings_vali[x,y]
                user_ratings_vali[x,y] = temp
                #print(temp)
print(user_ratings_vali,'\n', count,'\n', count/(user_ratings.shape[0]*user_ratings.shape[1]))

[[99.   99.   99.   ... 99.   99.   99.  ]
 [99.    4.08 99.   ... 99.   99.   99.  ]
 [99.   99.   99.   ... 99.   99.   99.  ]
 ...
 [99.   99.   99.   ... 99.   99.   99.  ]
 [99.   99.   99.   ... 99.   99.   99.  ]
 [37.   99.   99.   ... 99.   99.   99.  ]] 
 750 
 0.07425742574257425


In [114]:
def predict_rating(user_id,item_id):
    """ Predict a rating given a user_id and an item_id.
    """
    user_preference = latent_user_preferences[user_id]
    item_preference = latent_item_features[item_id]
    return user_preference.dot(item_preference)

def train(user_id, item_id, rating,alpha = 0.0001):
    
    #print (item_id)
    prediction_rating = predict_rating(user_id, item_id)
    err =  ( prediction_rating- rating );
    #print (err)
    user_pref_values = latent_user_preferences[user_id][:]
    latent_user_preferences[user_id] -= alpha * err * latent_item_features[item_id]
    latent_item_features[item_id] -= alpha * err * user_pref_values
    return err
    


def sgd(iterations = 100000):
    """ Iterate over all users and all items and train for 
        a certain number of iterations
    """
    err_mse_log = 0
    for iteration in range(0,iterations):
        error = []
        for user_id in range(0,latent_user_preferences.shape[0]):
            for item_id in range(0,latent_item_features.shape[0]):
                rating = user_ratings_copy[user_id][item_id]
                if(rating != 99.0):
                    err = train(user_id,item_id,rating)
                    error.append(err)
                    #print(rating)
        mse = (np.array(error) ** 2).mean()
        #print(iteration)
        if(iteration%1000 == 0 ):
            err_mse = mse - err_mse_log
            err_mse_log = mse
            print (iteration, ':=', mse, err_mse)
                    
                    
    

In [115]:
sgd()

0 := 102.64787729039328 102.64787729039328
1000 := 13.664407037192879 -88.98347025320041
2000 := 13.449147369034806 -0.21525966815807251
3000 := 13.392284623850616 -0.056862745184190544
4000 := 13.36568295176121 -0.02660167208940578
5000 := 13.348509889960347 -0.017173061800862754
6000 := 13.334623548508604 -0.013886341451742723
7000 := 13.321984382789875 -0.012639165718729473
8000 := 13.31012314485743 -0.011861237932444979
9000 := 13.299227893802001 -0.010895251055428545
10000 := 13.289650183395336 -0.009577710406665219
11000 := 13.281575090116874 -0.00807509327846212
12000 := 13.274942143453453 -0.00663294666342118
13000 := 13.269550409594933 -0.005391733858520098
14000 := 13.265171596516288 -0.004378813078645294
15000 := 13.261603061564378 -0.0035685349519098963


KeyboardInterrupt: 

In [116]:
latent_user_preferences

array([[ 1.255e+00,  2.296e+00, -1.690e+00,  3.148e+00, -4.341e-01],
       [ 3.186e+00,  9.444e-02,  2.021e+00, -1.540e-01,  1.730e+00],
       [ 2.237e-01,  7.588e-01,  4.561e+00, -8.151e-01,  6.036e-01],
       [ 1.212e+00,  5.862e-01,  1.413e+00,  1.350e+00, -7.108e-01],
       [ 1.279e+00,  8.315e-01,  2.349e+00,  1.583e+00,  1.011e+00],
       [ 2.117e+00,  1.254e+00, -2.186e+00,  1.923e+00,  2.300e+00],
       [ 4.212e-01,  7.757e-01,  2.884e+00, -6.361e-01,  9.679e-01],
       [ 4.545e+00,  3.327e+00, -2.145e-01,  2.149e+00,  3.041e+00],
       [ 9.018e-01,  1.775e+00,  3.122e-01,  2.569e+00,  1.378e+00],
       [ 8.969e-01,  9.902e-01,  2.959e+00,  3.902e-01,  8.529e-01],
       [ 6.475e-01,  9.298e-01,  2.229e+00,  7.249e-01, -9.486e-01],
       [ 1.917e+00,  1.198e+00,  7.056e-01,  1.737e+00,  1.274e+00],
       [ 2.468e-01,  7.654e-01,  3.408e+00,  6.407e-01, -2.340e-01],
       [ 3.128e+00,  1.816e+00,  2.771e+00, -1.222e-01,  1.380e-01],
       [ 1.879e+00,  1.041e+00,  2

In [117]:
predictions = latent_user_preferences.dot(latent_item_features.T)
predictions

array([[ 7.450e+01, -4.989e+00, -1.971e-01, ..., -1.592e+00, -4.984e+00,
         1.859e+00],
       [ 9.981e+01,  6.596e+00,  4.632e+00, ...,  3.123e+00,  5.199e-02,
         3.241e+00],
       [ 4.899e+01,  1.013e+01,  6.753e+00, ...,  4.290e+00,  5.660e+00,
         7.028e+00],
       ...,
       [ 3.709e+01,  1.786e+00, -9.979e-01, ..., -7.195e-02,  4.019e+00,
        -3.048e+00],
       [ 9.977e+01,  2.902e+00,  1.674e+00, ..., -2.333e+00,  1.196e+00,
        -1.879e-01],
       [ 3.453e+01, -5.263e+00, -3.608e+00, ..., -1.003e+00, -3.341e-01,
        -3.394e+00]])

In [99]:
values = [zip(user_ratings_copy[i], predictions[i]) for i in range(0,predictions.shape[0])]
comparison_data = pd.DataFrame(values)
comparison_data.columns = data.columns
comparison_data.applymap(lambda x: "(%2.3f|%2.3f)"%(x[0],x[1]))
#comparison_data.head()

0                1                 2                3    \
0     (74.000|73.955)  (-7.820|-6.749)     (8.790|1.793)  (-9.660|-6.861)   
1    (100.000|99.261)    (4.080|7.457)   (-0.290|-0.191)    (6.360|5.996)   
2     (99.000|78.384)   (99.000|8.956)    (99.000|5.437)   (99.000|9.383)   
3     (48.000|47.779)   (99.000|1.005)     (8.350|7.571)  (99.000|-0.656)   
4     (91.000|91.604)    (8.500|3.935)     (4.610|3.707)   (-4.170|3.576)   
5    (100.000|99.493)  (-6.170|-1.716)   (-3.540|-4.593)   (0.440|-4.636)   
6     (47.000|47.303)   (99.000|4.922)    (99.000|3.642)   (99.000|6.487)   
7   (100.000|100.690)    (6.840|0.763)     (3.160|0.633)  (99.000|-0.627)   
8    (99.000|100.442)  (-3.790|-2.823)   (99.000|-2.682)  (99.000|-3.933)   
9     (72.000|71.899)    (3.010|5.205)     (5.150|4.086)    (5.150|5.310)   
10    (99.000|-7.586)  (-2.910|-0.401)     (4.080|5.581)   (99.000|3.396)   
11   (100.000|99.431)    (1.310|1.871)     (1.800|2.561)    (2.570|0.471)   
12    (47.000|47.225)   (99.000|4.058)    (99.000|5.745)   (99.000|5.016)   
13  (100.000|100.482)   (9.220|11.035)    (9.270|10.867)    (9.220|9.230)   
14  (100.000|100.609)    (8.790|5.368)   (-5.780|-2.491)    (6.020|2.301)   
15   (100.000|99.378)   (-3.500|0.900)     (1.550|2.442)   (2.330|-0.441)   
16    (99.000|-6.588)  (99.000|-1.696)   (-9.270|-0.213)   (99.000|0.715)   
17   (100.000|98.819)    (3.160|4.509)     (7.620|1.804)   (99.000|3.617)   
18    (49.000|48.841)    (4.220|3.257)     (3.640|1.721)   (99.000|3.358)   
19    (53.000|53.221)  (99.000|-4.783)   (99.000|-1.246)  (99.000|-3.547)   
20    (55.000|55.272)  (99.000|-0.718)   (-0.730|-0.717)  (99.000|-1.679)   
21    (50.000|50.363)    (7.280|3.774)     (5.390|4.197)   (99.000|5.157)   
22    (72.000|73.059)    (2.720|3.355)     (4.170|5.585)    (6.500|4.495)   
23  (100.000|100.883)   (2.090|-2.085)   (-7.570|-2.226)  (99.000|-3.999)   
24    (74.000|74.129)   (99.000|1.300)    (-1.170|1.581)    (2.280|1.272)   
25    (67.000|67.025)   (99.000|4.647)     (5.490|4.293)    (3.450|4.309)   
26    (60.000|60.134)   (99.000|0.827)     (5.830|2.136)   (99.000|0.947)   
27    (72.000|72.295)   (0.490|-0.712)    (0.150|-1.203)   (0.150|-1.910)   
28    (54.000|53.838)  (99.000|-0.988)    (99.000|0.983)   (99.000|1.291)   
29    (46.000|46.084)   (99.000|4.238)     (4.080|5.526)   (99.000|4.693)   
..                ...              ...               ...              ...   
70  (100.000|100.597)    (3.500|1.094)     (6.210|3.534)  (-0.630|-1.038)   
71    (68.000|67.942)  (-6.210|-3.123)   (-0.100|-2.287)  (-5.290|-3.921)   
72   (100.000|99.830)   (5.440|-0.521)   (-2.670|-5.471)  (-7.960|-3.152)   
73    (67.000|66.933)    (9.270|4.354)     (9.170|6.640)   (99.000|8.471)   
74  (100.000|101.262)   (2.380|-0.515)    (-5.440|0.559)  (-8.110|-2.483)   
75    (48.000|48.084)  (99.000|-3.615)   (99.000|-0.765)  (99.000|-2.209)   
76   (100.000|99.386)  (-8.500|-4.063)   (-6.600|-6.725)  (-8.450|-6.479)   
77    (55.000|55.350)   (99.000|4.582)    (99.000|2.238)   (99.000|4.576)   
78  (100.000|100.873)    (2.280|3.512)   (99.000|-6.388)   (99.000|1.078)   
79    (53.000|52.776)  (99.000|-0.050)    (99.000|0.597)  (99.000|-0.820)   
80   (99.000|-13.088)  (99.000|-0.952)    (99.000|4.522)   (99.000|0.709)   
81    (53.000|52.964)   (3.450|-5.124)     (6.070|0.614)  (-9.270|-6.250)   
82  (100.000|100.220)    (3.060|1.772)     (6.500|1.080)  (-7.910|-3.571)   
83    (72.000|71.618)   (-7.670|1.282)    (-6.990|0.400)   (-1.410|3.191)   
84    (41.000|41.471)   (99.000|3.457)    (99.000|3.392)   (99.000|2.230)   
85    (72.000|71.342)  (-1.500|-0.217)    (3.300|-1.580)  (99.000|-1.049)   
86   (100.000|99.607)    (2.820|5.546)     (5.440|1.989)    (7.570|4.535)   
87    (74.000|74.787)   (6.890|-1.482)    (-9.660|0.006)   (0.150|-3.564)   
88    (72.000|72.003)  (-6.070|-0.122)   (-5.580|-0.129)  (-6.170|-3.028)   
89   (100.000|99.852)   (-0.920|4.896)     (1.650|4.357)   (99.000|4.538)   
90    (68.000|

In [118]:
values = [zip(user_ratings_vali[i], predictions[i]) for i in range(0,predictions.shape[0])]
comparison_data = pd.DataFrame(values)
comparison_data_err = []
for x in range(0, comparison_data.shape[1]):
    for y in range(0, comparison_data.shape[0]):
        if (comparison_data[x][y][0] == 99.0):
            comparison_data[x][y] = (0,0)
        else:
            comparison_data_err.append(comparison_data[x][y][0] - comparison_data[x][y][1])
mse = (np.array(comparison_data_err) ** 2).mean()
comparison_data.columns = data.columns
comparison_data.applymap(lambda x: ["(%2.3f|%2.3f)"%(x[0],x[1]) ])

0                 1                  2    \
0       [(0.000|0.000)]   [(0.000|0.000)]    [(0.000|0.000)]   
1       [(0.000|0.000)]   [(4.080|6.596)]    [(0.000|0.000)]   
2       [(0.000|0.000)]   [(0.000|0.000)]    [(0.000|0.000)]   
3       [(0.000|0.000)]   [(0.000|0.000)]    [(8.350|4.170)]   
4       [(0.000|0.000)]   [(0.000|0.000)]    [(0.000|0.000)]   
5       [(0.000|0.000)]   [(0.000|0.000)]    [(0.000|0.000)]   
6       [(0.000|0.000)]   [(0.000|0.000)]    [(0.000|0.000)]   
7   [(100.000|199.540)]   [(0.000|0.000)]    [(0.000|0.000)]   
8       [(0.000|0.000)]   [(0.000|0.000)]    [(0.000|0.000)]   
9       [(0.000|0.000)]   [(0.000|0.000)]    [(0.000|0.000)]   
10      [(0.000|0.000)]  [(-2.910|4.394)]    [(0.000|0.000)]   
11      [(0.000|0.000)]   [(0.000|0.000)]    [(1.800|1.514)]   
12      [(0.000|0.000)]   [(0.000|0.000)]    [(0.000|0.000)]   
13      [(0.000|0.000)]   [(0.000|0.000)]    [(9.270|9.180)]   
14      [(0.000|0.000)]   [(0.000|0.000)]    [(0.000|0.000)]   
15      [(0.000|0.000)]   [(0.000|0.000)]    [(0.000|0.000)]   
16      [(0.000|0.000)]   [(0.000|0.000)]    [(0.000|0.000)]   
17      [(0.000|0.000)]   [(0.000|0.000)]    [(0.000|0.000)]   
18      [(0.000|0.000)]   [(0.000|0.000)]    [(0.000|0.000)]   
19      [(0.000|0.000)]   [(0.000|0.000)]    [(0.000|0.000)]   
20      [(0.000|0.000)]   [(0.000|0.000)]    [(0.000|0.000)]   
21      [(0.000|0.000)]   [(7.280|4.121)]    [(0.000|0.000)]   
22      [(0.000|0.000)]   [(2.720|5.356)]    [(0.000|0.000)]   
23      [(0.000|0.000)]   [(0.000|0.000)]  [(-7.570|-1.023)]   
24      [(0.000|0.000)]   [(0.000|0.000)]    [(0.000|0.000)]   
25    [(67.000|20.469)]   [(0.000|0.000)]    [(0.000|0.000)]   
26      [(0.000|0.000)]   [(0.000|0.000)]    [(0.000|0.000)]   
27      [(0.000|0.000)]   [(0.000|0.000)]    [(0.000|0.000)]   
28      [(0.000|0.000)]   [(0.000|0.000)]    [(0.000|0.000)]   
29      [(0.000|0.000)]   [(0.000|0.000)]    [(0.000|0.000)]   
..                  ...               ...                ...   
70      [(0.000|0.000)]   [(0.000|0.000)]    [(0.000|0.000)]   
71      [(0.000|0.000)]   [(0.000|0.000)]    [(0.000|0.000)]   
72      [(0.000|0.000)]  [(5.440|-2.797)]    [(0.000|0.000)]   
73      [(0.000|0.000)]   [(0.000|0.000)]    [(0.000|0.000)]   
74      [(0.000|0.000)]   [(0.000|0.000)]    [(0.000|0.000)]   
75      [(0.000|0.000)]   [(0.000|0.000)]    [(0.000|0.000)]   
76      [(0.000|0.000)]   [(0.000|0.000)]    [(0.000|0.000)]   
77      [(0.000|0.000)]   [(0.000|0.000)]    [(0.000|0.000)]   
78      [(0.000|0.000)]   [(0.000|0.000)]    [(0.000|0.000)]   
79    [(53.000|91.615)]   [(0.000|0.000)]    [(0.000|0.000)]   
80      [(0.000|0.000)]   [(0.000|0.000)]    [(0.000|0.000)]   
81      [(0.000|0.000)]   [(0.000|0.000)]    [(0.000|0.000)]   
82  [(100.000|522.665)]   [(0.000|0.000)]    [(0.000|0.000)]   
83      [(0.000|0.000)]  [(-7.670|5.385)]    [(0.000|0.000)]   
84      [(0.000|0.000)]   [(0.000|0.000)]    [(0.000|0.000)]   
85      [(0.000|0.000)]  [(-1.500|0.571)]    [(0.000|0.000)]   
86      [(0.000|0.000)]   [(0.000|0.000)]    [(0.000|0.000)]   
87      [(0.000|0.000)]   [(0.000|0.000)]   [(-9.660|0.908)]   
88      [(0.000|0.000)]   [(0.000|0.000)]    [(0.000|0.000)]   
89      [(0.000|0.000)]   [(0.000|0.000)]    [(0.000|0.000)]   
90      [(0.000|0.000)]   [(0.000|0.000)]    [(0.000|0.000)]   
91      [(0.000|0.000)]   [(0.000|0.000)]    [(0.000|0.000)]   
92      [(0.000|0.000)]   [(0.000|0.000)]    [(0.000|0.000)]   
93      [(0.000|0.000)]   [(0.000|0.000)]    [(0.000|0.000)]   
94      [(0.000|0.000)]   [(8.160|7.144)]    [(0.000|0.000)]   
95      [(0.000|0.000)]   [(0.000|0.000)]    [(0.000|0.000)]   
96      [(0.000|0.000)]   [(0.000|0.000)]   [(-5.000|2.746)]   
97      [(0.000|0.000)]   [(0.000|0.000)]    [(0.000|0.000)]   
98      [(0.000|0.000)]   [(0.000|0.000)]    [(0.000|0.000)]   
99    [(37.000|34.535)]   [(0.000|0.000)]    [(0.000|0.000)]   

                  3                  4             

In [119]:
mse


348.54864599904784

In [56]:
comparison_data[99][99][0] == 99
comparison_data.shape

(100, 101)

In [31]:
data.columns

Index(['74', '-7.82', '8.79', '-9.66', '-8.16', '-7.52', '-8.5', '-9.85',
       '4.17', '-8.98',
       ...
       '2.82.2', '99.18', '99.19', '99.20', '99.21', '99.22', '-5.63', '99.23',
       '99.24', '99.25'],
      dtype='object', length=101)

In [32]:
data.head()

74  -7.82   8.79  -9.66  -8.16  -7.52  -8.5  -9.85  4.17  -8.98  ...    \
0  100   4.08  -0.29   6.36   4.37  -2.38 -9.66  -0.73 -5.34   8.88  ...     
1   49  99.00  99.00  99.00  99.00   9.03  9.27   9.03  9.27  99.00  ...     
2   48  99.00   8.35  99.00  99.00   1.80  8.16  -2.82  6.21  99.00  ...     
3   91   8.50   4.61  -4.17  -5.39   1.36  1.60   7.04  4.61  -0.44  ...     
4  100  -6.17  -3.54   0.44  -8.50  -7.09 -4.32  -8.69 -0.87  -6.65  ...     

   2.82.2  99.18  99.19  99.20  99.21  99.22  -5.63  99.23  99.24  99.25  
0    2.82  -4.95  -0.29   7.86  -0.19  -2.14   3.06   0.34  -4.32   1.07  
1   99.00  99.00  99.00   9.08  99.00  99.00  99.00  99.00  99.00  99.00  
2   99.00  99.00  99.00   0.53  99.00  99.00  99.00  99.00  99.00  99.00  
3    5.19   5.58   4.27   5.19   5.73   1.55   3.11   6.55   1.80   1.60  
4   -3.54  -6.89  -0.68  -2.96  -2.18  -3.35   0.05  -9.08  -5.05  -3.45  

[5 rows x 101 columns]