- import nesssary model

In [1]:
import pandas as pd
import numpy as np
from IPython.display import Image
np.set_printoptions(precision = 3)

- load data

In [2]:
data = pd.read_csv("jester-data-1.csv", header=None)
d = data.to_latex()
text_file = open("Output_lab4_test.txt", "w")
text_file.write(d)
text_file.close()

In [3]:
data.head()

0      1      2      3      4     5     6     7     8      9    ...    \
0   74  -7.82   8.79  -9.66  -8.16 -7.52 -8.50 -9.85  4.17  -8.98  ...     
1  100   4.08  -0.29   6.36   4.37 -2.38 -9.66 -0.73 -5.34   8.88  ...     
2   49  99.00  99.00  99.00  99.00  9.03  9.27  9.03  9.27  99.00  ...     
3   48  99.00   8.35  99.00  99.00  1.80  8.16 -2.82  6.21  99.00  ...     
4   91   8.50   4.61  -4.17  -5.39  1.36  1.60  7.04  4.61  -0.44  ...     

     91     92     93     94     95     96     97     98     99     100  
0   2.82  99.00  99.00  99.00  99.00  99.00  -5.63  99.00  99.00  99.00  
1   2.82  -4.95  -0.29   7.86  -0.19  -2.14   3.06   0.34  -4.32   1.07  
2  99.00  99.00  99.00   9.08  99.00  99.00  99.00  99.00  99.00  99.00  
3  99.00  99.00  99.00   0.53  99.00  99.00  99.00  99.00  99.00  99.00  
4   5.19   5.58   4.27   5.19   5.73   1.55   3.11   6.55   1.80   1.60  

[5 rows x 101 columns]

In [ ]:
#user_ratings = data.values
user_ratings = data.values[0:100]

In [ ]:
user_ratings_vali = np.zeros(user_ratings.shape) + 99.0
user_ratings_copy = user_ratings.copy() 
count = 0
for x in range(0,user_ratings.shape[0]):
    for y in range(0,user_ratings.shape[1]):
        if (user_ratings_copy[x,y]!=99.0):
            if (np.random.random() > 0.9):
                count += 1
                temp = user_ratings_copy[x,y]
                user_ratings_copy[x,y] = user_ratings_vali[x,y]
                user_ratings_vali[x,y] = temp
                #print(temp)
print(user_ratings_vali,'\n', count,'\n', count/(user_ratings.shape[0]*user_ratings.shape[1]))

In [25]:
n_features = 7
latent_user_preferences = np.random.random((user_ratings.shape[0], n_features))
latent_item_features = np.random.random((user_ratings.shape[1],n_features))

In [26]:
print('user_ratings.shape:           ',user_ratings.shape)
print('latent_user_preferences.shape:',latent_user_preferences.shape)
print('latent_item_features.shape:   ',latent_item_features.shape)

user_ratings.shape:            (100, 101)
latent_user_preferences.shape: (100, 7)
latent_item_features.shape:    (101, 7)


In [27]:
latent_user_preferences

array([[9.239e-01, 4.943e-01, 6.435e-01, 6.961e-01, 5.443e-02, 8.376e-01,
        5.255e-01],
       [3.913e-02, 5.495e-01, 1.593e-01, 9.503e-01, 7.349e-01, 8.453e-01,
        8.617e-01],
       [9.006e-02, 8.293e-01, 8.424e-01, 1.584e-01, 5.991e-01, 9.561e-01,
        1.582e-01],
       [7.744e-02, 2.909e-01, 5.043e-01, 4.883e-01, 5.814e-01, 6.506e-01,
        7.357e-01],
       [9.942e-01, 6.606e-01, 9.319e-01, 8.863e-01, 2.382e-01, 9.255e-01,
        6.333e-01],
       [1.231e-02, 8.169e-01, 8.690e-01, 3.932e-01, 2.780e-01, 6.317e-01,
        3.283e-01],
       [7.416e-01, 8.776e-01, 6.285e-01, 8.264e-01, 5.273e-01, 1.297e-01,
        7.580e-01],
       [8.045e-01, 1.003e-02, 5.911e-01, 5.315e-01, 8.530e-01, 1.682e-01,
        6.027e-01],
       [9.676e-01, 2.444e-01, 6.935e-01, 9.544e-01, 7.692e-01, 1.928e-01,
        6.668e-01],
       [8.789e-01, 8.298e-01, 7.537e-01, 8.233e-01, 8.891e-01, 7.878e-01,
        2.857e-01],
       [4.757e-01, 7.203e-01, 8.556e-01, 7.584e-01, 6.644e-0

In [28]:
latent_item_features

array([[9.788e-01, 1.448e-01, 9.205e-01, 4.648e-02, 1.812e-01, 6.062e-01,
        3.868e-01],
       [9.957e-01, 3.220e-01, 6.407e-01, 3.344e-01, 4.632e-01, 1.610e-01,
        5.807e-01],
       [7.092e-01, 6.053e-01, 5.075e-01, 6.870e-01, 4.913e-02, 7.001e-01,
        3.854e-01],
       [5.165e-01, 7.662e-01, 7.502e-01, 4.049e-01, 3.925e-01, 5.917e-01,
        8.953e-01],
       [6.278e-03, 7.843e-01, 5.147e-01, 2.688e-01, 4.440e-01, 5.314e-01,
        7.915e-01],
       [1.918e-01, 1.369e-01, 6.471e-01, 2.353e-01, 4.831e-01, 6.530e-01,
        3.535e-01],
       [1.844e-01, 1.869e-01, 9.683e-01, 4.895e-01, 4.969e-01, 5.314e-01,
        3.083e-01],
       [5.893e-02, 2.617e-01, 8.218e-01, 1.738e-01, 2.131e-01, 8.694e-01,
        3.523e-01],
       [6.917e-01, 3.025e-01, 7.597e-01, 5.425e-01, 1.760e-01, 9.151e-01,
        5.358e-01],
       [3.657e-01, 2.417e-01, 8.619e-01, 6.525e-01, 3.460e-01, 2.507e-02,
        8.996e-01],
       [9.827e-01, 5.230e-01, 1.801e-02, 9.607e-01, 4.211e-0

In [29]:
user_ratings, user_ratings.shape

(array([[ 74.  ,  -7.82,   8.79, ...,  99.  ,  99.  ,  99.  ],
        [100.  ,   4.08,  -0.29, ...,   0.34,  -4.32,   1.07],
        [ 49.  ,  99.  ,  99.  , ...,  99.  ,  99.  ,  99.  ],
        ...,
        [ 37.  ,  99.  ,  99.  , ...,  99.  ,  99.  ,  99.  ],
        [100.  ,   3.3 ,   1.31, ...,  -0.44,   1.17,   6.5 ],
        [ 37.  ,  99.  ,  99.  , ...,  99.  ,  99.  ,  99.  ]]), (100, 101))

In [30]:
np.random.random()

0.3532728797898732

In [32]:
def predict_rating(user_id,item_id):
    """ Predict a rating given a user_id and an item_id.
    """
    user_preference = latent_user_preferences[user_id]
    item_preference = latent_item_features[item_id]
    return user_preference.dot(item_preference)

def train(user_id, item_id, rating,alpha = 0.0001):
    
    #print (item_id)
    prediction_rating = predict_rating(user_id, item_id)
    err =  ( prediction_rating- rating );
    #print (err)
    user_pref_values = latent_user_preferences[user_id][:]
    latent_user_preferences[user_id] -= alpha * err * latent_item_features[item_id]
    latent_item_features[item_id] -= alpha * err * user_pref_values
    return err
    


def sgd(iterations = 100000):
    """ Iterate over all users and all items and train for 
        a certain number of iterations
    """
    err_mse_log = 0
    for iteration in range(0,iterations):
        error = []
        for user_id in range(0,latent_user_preferences.shape[0]):
            for item_id in range(0,latent_item_features.shape[0]):
                rating = user_ratings_copy[user_id][item_id]
                if(rating != 99.0):
                    err = train(user_id,item_id,rating)
                    error.append(err)
                    #print(rating)
        mse = (np.array(error) ** 2).mean()
        #print(iteration)
        if(iteration%1000 == 0 ):
            err_mse = mse - err_mse_log
            err_mse_log = mse
            print (iteration, ':=', mse, err_mse)
                    
                    
    

In [33]:
sgd()

0 := 98.72613765036839 98.72613765036839
1000 := 11.811444225385326 -86.91469342498306
2000 := 11.346600756490197 -0.46484346889512906
3000 := 11.257884969082497 -0.08871578740770047
4000 := 11.220184521145658 -0.0377004479368388
5000 := 11.18912140717361 -0.031063113972047418
6000 := 11.161610301471041 -0.027511105702568983
7000 := 11.140625147008507 -0.020985154462534794
8000 := 11.12689156783382 -0.013733579174687094
9000 := 11.118920237366297 -0.007971330467523075
10000 := 11.114575397186048 -0.00434484018024861
11000 := 11.112183278548256 -0.0023921186377915404
12000 := 11.110773662204332 -0.0014096163439241138
13000 := 11.109856460445506 -0.0009172017588259251
14000 := 11.109194715601298 -0.0006617448442085561
15000 := 11.108673222150866 -0.0005214934504316204
16000 := 11.108233980035548 -0.00043924211531809476
17000 := 11.107846122682417 -0.0003878573531306273
18000 := 11.10749202618282 -0.0003540964995973894
19000 := 11.10716079444954 -0.0003312317332806458
20000 := 11.10684510

In [34]:
latent_user_preferences

array([[ 1.572e+00, -9.643e-01,  2.463e+00, -7.934e-02,  4.636e-01,
         1.123e+00,  1.155e-02],
       [ 6.208e-01,  6.911e-01, -9.087e-01,  1.770e+00,  8.604e-01,
         3.609e-01,  1.672e-01],
       [-1.269e-03,  1.788e+00, -9.203e-01,  5.192e-01,  9.121e-01,
         2.864e-01,  2.912e+00],
       [ 2.225e-02,  3.020e-01,  7.780e-01, -1.019e-01,  1.227e+00,
         1.303e+00,  1.530e+00],
       [ 2.047e+00,  7.770e-01,  2.066e-01,  5.124e-01,  5.901e-01,
         9.359e-01,  2.174e+00],
       [ 2.069e+00, -1.434e-01,  1.674e+00,  1.255e+00, -1.710e-01,
         2.102e+00, -8.420e-01],
       [ 4.239e-01,  1.148e+00, -2.024e-01,  1.310e+00,  5.189e-01,
        -2.729e-01,  1.507e+00],
       [ 1.777e+00, -9.769e-01,  1.524e+00,  1.654e+00,  6.857e-01,
         1.600e+00,  2.972e-01],
       [ 1.745e+00,  1.038e+00,  1.607e+00,  3.757e-01,  6.810e-01,
         1.444e+00,  2.300e-01],
       [ 3.502e-01,  1.429e+00,  4.231e-01,  1.145e+00,  7.879e-01,
         4.143e-01,  1.

In [35]:
predictions = latent_user_preferences.dot(latent_item_features.T)
predictions

array([[ 7.499e+01, -3.093e+00, -9.999e-01, ..., -4.955e+00, -1.506e+00,
        -4.025e-02],
       [ 4.377e+01,  4.554e+00,  1.797e+00, ...,  1.058e+00, -4.459e+00,
         2.601e+00],
       [ 4.917e+01,  9.952e+00,  9.085e+00, ...,  2.876e+00,  8.791e+00,
         6.365e+00],
       ...,
       [ 3.763e+01, -1.022e+01, -1.350e+01, ...,  8.973e+00, -1.112e+01,
         1.301e+00],
       [ 9.933e+01,  3.251e+00,  1.940e+00, ..., -2.305e+00,  1.453e+00,
         1.953e-01],
       [ 3.683e+01, -3.320e+00, -3.950e+00, ..., -1.068e+00, -1.525e+00,
        -4.472e+00]])

In [38]:
values = [zip(user_ratings_copy[i], predictions[i]) for i in range(0,predictions.shape[0])]
comparison_data = pd.DataFrame(values)
comparison_data.columns = data.columns
comparison_data.applymap(lambda x: "(%2.3f|%2.3f)"%(x[0],x[1]))
#comparison_data.head()

0                 1                 2                3    \
0     (74.000|74.989)   (-7.820|-3.093)    (8.790|-1.000)  (99.000|-2.617)   
1     (99.000|43.768)     (4.080|4.554)    (-0.290|1.797)    (6.360|5.671)   
2     (49.000|49.167)    (99.000|9.952)    (99.000|9.085)   (99.000|5.332)   
3     (99.000|58.976)    (99.000|3.473)     (8.350|5.507)   (99.000|1.188)   
4     (91.000|91.002)     (8.500|6.060)     (4.610|4.390)   (-4.170|2.177)   
5    (100.000|99.561)   (-6.170|-3.101)   (-3.540|-5.887)   (0.440|-4.403)   
6     (47.000|47.431)    (99.000|6.688)    (99.000|5.337)   (99.000|5.552)   
7   (100.000|100.272)     (6.840|3.279)     (3.160|2.691)    (9.170|3.409)   
8    (100.000|99.981)   (-3.790|-3.136)   (-3.540|-3.980)  (-9.420|-4.402)   
9     (72.000|71.704)     (3.010|6.049)     (5.150|5.408)    (5.150|3.690)   
10    (36.000|35.936)    (-2.910|1.227)    (99.000|2.637)   (99.000|4.143)   
11   (100.000|99.302)     (1.310|1.532)     (1.800|1.334)    (2.570|1.124)   
12    (47.000|47.498)    (99.000|4.773)    (99.000|5.764)   (99.000|3.541)   
13   (99.000|199.127)     (9.220|9.547)     (9.270|7.593)   (9.220|11.052)   
14  (100.000|100.138)     (8.790|7.330)    (-5.780|2.370)    (6.020|2.005)   
15   (100.000|99.109)    (99.000|2.142)     (1.550|2.744)    (2.330|2.183)   
16    (51.000|50.367)   (99.000|-0.753)   (-9.270|-0.978)  (99.000|-0.927)   
17    (99.000|33.627)     (3.160|2.619)     (7.620|2.973)    (3.790|3.009)   
18    (49.000|49.035)     (4.220|1.920)    (99.000|0.080)   (99.000|1.388)   
19    (53.000|53.099)    (99.000|1.531)     (7.620|4.720)   (99.000|0.383)   
20    (55.000|55.133)     (2.570|0.451)   (-0.730|-0.145)  (99.000|-0.953)   
21    (50.000|50.182)     (7.280|5.880)     (5.390|5.371)   (99.000|4.543)   
22    (72.000|72.988)     (2.720|5.169)     (4.170|5.026)    (6.500|4.162)   
23  (100.000|100.250)    (2.090|-2.736)   (99.000|-3.505)  (99.000|-6.672)   
24    (74.000|74.660)   (-3.930|-0.241)   (-1.170|-0.445)    (2.280|0.036)   
25    (67.000|67.018)    (99.000|4.788)     (5.490|4.978)    (3.450|3.705)   
26    (99.000|56.046)    (99.000|9.483)    (99.000|9.706)   (99.000|2.872)   
27    (72.000|71.867)     (0.490|1.824)     (0.150|1.417)    (0.150|1.271)   
28    (54.000|54.063)    (99.000|3.944)    (99.000|4.193)   (99.000|3.039)   
29    (46.000|46.200)    (99.000|3.273)     (4.080|3.871)   (99.000|4.073)   
..                ...               ...               ...              ...   
70  (100.000|101.017)     (3.500|1.560)     (6.210|2.098)   (-0.630|1.069)   
71    (68.000|68.151)   (-6.210|-4.174)   (-0.100|-5.315)  (-5.290|-2.700)   
72    (99.000|66.242)    (5.440|-1.662)   (-2.670|-4.810)  (-7.960|-4.015)   
73    (67.000|67.092)     (9.270|7.249)     (9.170|8.062)   (9.270|10.891)   
74   (99.000|202.700)     (2.380|1.013)   (-5.440|-1.996)  (-8.110|-3.402)   
75    (48.000|47.901)    (99.000|6.004)    (99.000|4.498)  (99.000|-4.691)   
76   (100.000|99.425)  (-8.500|-10.256)  (-6.600|-12.552)  (-8.450|-7.996)   
77    (55.000|55.222)    (99.000|6.485)    (99.000|4.028)  (99.000|-0.054)   
78    (99.000|87.766)     (2.280|5.127)    (1.700|-1.114)  (-5.530|-4.631)   
79    (53.000|52.937)    (99.000|2.772)    (99.000|2.493)  (99.000|-1.224)   
80    (38.000|38.202)    (99.000|0.766)    (99.000|2.140)   (99.000|1.951)   
81    (53.000|53.044)     (3.450|1.002)     (6.070|1.984)  (-9.270|-6.586)   
82  (100.000|100.521)     (3.060|5.020)     (6.500|4.485)  (-7.910|-2.124)   
83    (72.000|71.607)   (-7.670|-1.844)   (-6.990|-2.681)   (-1.410|4.052)   
84    (41.000|41.453)    (99.000|3.397)    (99.000|4.843)   (99.000|2.385)   
85    (72.000|71.636)   (-1.500|-0.479)    (3.300|-1.775)   (3.350|-1.089)   
86   (100.000|98.653)     (2.820|6.550)     (5.440|4.245)   (99.000|2.462)   
87    (74.000|74.684)    (6.890|-2.048)   (-9.660|-1.254)   (0.150|-2.507)   
88    (72.000|72.400)   (-6.070|-1.564)   (-5.580|-2.661)  (-6.170|-4.495)   
89   (100.000|99.889)    (-0.920|3.062) 

In [36]:
values = [zip(user_ratings_vali[i], predictions[i]) for i in range(0,predictions.shape[0])]
comparison_data = pd.DataFrame(values)
comparison_data_err = []
for x in range(0, comparison_data.shape[1]):
    for y in range(0, comparison_data.shape[0]):
        if (comparison_data[x][y][0] == 99.0):
            comparison_data[x][y] = (0,0)
        else:
            comparison_data_err.append(comparison_data[x][y][0] - comparison_data[x][y][1])
mse = (np.array(comparison_data_err) ** 2).mean()
comparison_data.columns = data.columns
comparison_data.applymap(lambda x: ["(%2.3f|%2.3f)"%(x[0],x[1]) ])

0                  1                  2    \
0       [(0.000|0.000)]    [(0.000|0.000)]    [(0.000|0.000)]   
1    [(100.000|43.768)]    [(0.000|0.000)]    [(0.000|0.000)]   
2       [(0.000|0.000)]    [(0.000|0.000)]    [(0.000|0.000)]   
3     [(48.000|58.976)]    [(0.000|0.000)]    [(0.000|0.000)]   
4       [(0.000|0.000)]    [(0.000|0.000)]    [(0.000|0.000)]   
5       [(0.000|0.000)]    [(0.000|0.000)]    [(0.000|0.000)]   
6       [(0.000|0.000)]    [(0.000|0.000)]    [(0.000|0.000)]   
7       [(0.000|0.000)]    [(0.000|0.000)]    [(0.000|0.000)]   
8       [(0.000|0.000)]    [(0.000|0.000)]    [(0.000|0.000)]   
9       [(0.000|0.000)]    [(0.000|0.000)]    [(0.000|0.000)]   
10      [(0.000|0.000)]    [(0.000|0.000)]    [(4.080|2.637)]   
11      [(0.000|0.000)]    [(0.000|0.000)]    [(0.000|0.000)]   
12      [(0.000|0.000)]    [(0.000|0.000)]    [(0.000|0.000)]   
13  [(100.000|199.127)]    [(0.000|0.000)]    [(0.000|0.000)]   
14      [(0.000|0.000)]    [(0.000|0.000)]    [(0.000|0.000)]   
15      [(0.000|0.000)]   [(-3.500|2.142)]    [(0.000|0.000)]   
16      [(0.000|0.000)]    [(0.000|0.000)]    [(0.000|0.000)]   
17   [(100.000|33.627)]    [(0.000|0.000)]    [(0.000|0.000)]   
18      [(0.000|0.000)]    [(0.000|0.000)]    [(3.640|0.080)]   
19      [(0.000|0.000)]    [(0.000|0.000)]    [(0.000|0.000)]   
20      [(0.000|0.000)]    [(0.000|0.000)]    [(0.000|0.000)]   
21      [(0.000|0.000)]    [(0.000|0.000)]    [(0.000|0.000)]   
22      [(0.000|0.000)]    [(0.000|0.000)]    [(0.000|0.000)]   
23      [(0.000|0.000)]    [(0.000|0.000)]  [(-7.570|-3.505)]   
24      [(0.000|0.000)]    [(0.000|0.000)]    [(0.000|0.000)]   
25      [(0.000|0.000)]    [(0.000|0.000)]    [(0.000|0.000)]   
26    [(60.000|56.046)]    [(0.000|0.000)]    [(5.830|9.706)]   
27      [(0.000|0.000)]    [(0.000|0.000)]    [(0.000|0.000)]   
28      [(0.000|0.000)]    [(0.000|0.000)]    [(0.000|0.000)]   
29      [(0.000|0.000)]    [(0.000|0.000)]    [(0.000|0.000)]   
..                  ...                ...                ...   
70      [(0.000|0.000)]    [(0.000|0.000)]    [(0.000|0.000)]   
71      [(0.000|0.000)]    [(0.000|0.000)]    [(0.000|0.000)]   
72   [(100.000|66.242)]    [(0.000|0.000)]    [(0.000|0.000)]   
73      [(0.000|0.000)]    [(0.000|0.000)]    [(0.000|0.000)]   
74  [(100.000|202.700)]    [(0.000|0.000)]    [(0.000|0.000)]   
75      [(0.000|0.000)]    [(0.000|0.000)]    [(0.000|0.000)]   
76      [(0.000|0.000)]    [(0.000|0.000)]    [(0.000|0.000)]   
77      [(0.000|0.000)]    [(0.000|0.000)]    [(0.000|0.000)]   
78   [(100.000|87.766)]    [(0.000|0.000)]    [(0.000|0.000)]   
79      [(0.000|0.000)]    [(0.000|0.000)]    [(0.000|0.000)]   
80      [(0.000|0.000)]    [(0.000|0.000)]    [(0.000|0.000)]   
81      [(0.000|0.000)]    [(0.000|0.000)]    [(0.000|0.000)]   
82      [(0.000|0.000)]    [(0.000|0.000)]    [(0.000|0.000)]   
83      [(0.000|0.000)]    [(0.000|0.000)]    [(0.000|0.000)]   
84      [(0.000|0.000)]    [(0.000|0.000)]    [(0.000|0.000)]   
85      [(0.000|0.000)]    [(0.000|0.000)]    [(0.000|0.000)]   
86      [(0.000|0.000)]    [(0.000|0.000)]    [(0.000|0.000)]   
87      [(0.000|0.000)]    [(0.000|0.000)]    [(0.000|0.000)]   
88      [(0.000|0.000)]    [(0.000|0.000)]    [(0.000|0.000)]   
89      [(0.000|0.000)]    [(0.000|0.000)]    [(0.000|0.000)]   
90      [(0.000|0.000)]  [(-3.160|-0.127)]    [(0.000|0.000)]   
91      [(0.000|0.000)]    [(0.000|0.000)]    [(0.000|0.000)]   
92      [(0.000|0.000)]    [(0.000|0.000)]    [(0.000|0.000)]   
93    [(69.000|26.639)]    [(0.000|0.000)]   [(6.020|-0.887)]   
94      [(0.000|0.000)]    [(0.000|0.000)]    [(2.280|3.334)]   
95   [(73.000|319.564)]    [(0.000|0.000)]    [(0.000|0.000)]   
96      [(0.000|0.000)]    [(3.540|0.032)]    [(0.000|0.000)]   
97      [(0.000|0.000)]    [(0.000|0.000)]    [(0.000|0.000)]   
98      [(0.000|0.000)]    [(0.000|0.000)]    [(0.000|0.000)]   
99      [(0.000|0.000)]    [(0.000|0.000)]    [(0.000|0

In [37]:
mse


158.55902514891935

In [39]:
predictions

array([[ 7.499e+01, -3.093e+00, -9.999e-01, ..., -4.955e+00, -1.506e+00,
        -4.025e-02],
       [ 4.377e+01,  4.554e+00,  1.797e+00, ...,  1.058e+00, -4.459e+00,
         2.601e+00],
       [ 4.917e+01,  9.952e+00,  9.085e+00, ...,  2.876e+00,  8.791e+00,
         6.365e+00],
       ...,
       [ 3.763e+01, -1.022e+01, -1.350e+01, ...,  8.973e+00, -1.112e+01,
         1.301e+00],
       [ 9.933e+01,  3.251e+00,  1.940e+00, ..., -2.305e+00,  1.453e+00,
         1.953e-01],
       [ 3.683e+01, -3.320e+00, -3.950e+00, ..., -1.068e+00, -1.525e+00,
        -4.472e+00]])

In [46]:
latent_item_features

array([[ 1.677e+01,  9.843e+00,  1.512e+01,  1.396e+01,  1.001e+01,
         1.537e+01,  8.488e+00],
       [-6.697e-01, -1.463e+00, -1.333e+00,  2.450e+00, -2.101e-01,
         7.345e-02,  3.516e+00],
       [-1.539e+00, -2.265e+00, -2.469e-01,  1.527e+00,  1.079e+00,
        -5.172e-01,  3.872e+00],
       [-4.524e-01, -2.111e+00, -1.112e+00,  2.829e+00,  1.982e+00,
        -1.707e+00,  1.818e+00],
       [-1.238e+00,  6.376e-01, -1.209e+00,  2.425e+00,  1.526e+00,
        -2.503e+00,  6.170e-01],
       [-4.505e+00,  1.681e+00,  2.490e-01,  1.895e+00,  1.367e-01,
         7.615e-01,  1.509e+00],
       [-4.304e-01,  3.071e+00,  1.030e+00, -2.353e+00,  8.645e-01,
        -1.125e+00,  1.742e+00],
       [-4.463e-01, -1.264e+00, -5.354e-01,  7.419e-01, -5.704e-01,
        -8.961e-01,  3.894e+00],
       [-5.261e-01, -1.049e+00, -1.648e+00,  2.748e+00, -4.285e-01,
         2.868e-01,  1.261e+00],
       [ 4.895e-02,  1.025e+00, -1.852e+00,  3.283e+00, -1.011e-01,
        -2.880e+00,  2.

In [43]:
np.savetxt("predictions_7f_10.csv", predictions, delimiter=",")

In [45]:
np.savetxt("latent_user_preferences_7f_10.csv", latent_user_preferences, delimiter=",")

In [47]:
np.savetxt("latent_item_features_7f_10.csv", latent_item_features, delimiter=",")